apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-ingress-fintech
  namespace: nginx-ingress
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-ingress-fintech
  template:
    metadata:
      labels:
        app: nginx-ingress-fintech
    spec:
      serviceAccountName: nginx-ingress
      containers:
      - image: cloudadc/nginx-plus-ingress:1.7.2
        name: nginx-ingress
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
        - name: monitor
          containerPort: 8898
        securityContext:
          allowPrivilegeEscalation: true
          runAsUser: 101 
          capabilities:
            drop:
            - ALL
            add:
            - NET_BIND_SERVICE
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        args:
          - -nginx-plus
          - -nginx-configmaps=$(POD_NAMESPACE)/nginx-config
          - -default-server-tls-secret=$(POD_NAMESPACE)/default-server-secret
          - -ingress-class=fintech
          - -use-ingress-class-only
          - -nginx-status=true
          - -nginx-status-allow-cidrs=0.0.0.0/0
          - -nginx-status-port=8898
